### ISSUE TITLE
"with the same title ID  but a different filename already exists in the output directory"

### ISSUE THREAD

**Issue by a5723797** [nicoboss/nsz#28] opened 2019-11-10 10:33 UTC
When doing the conversion from nsp to nsz, it sometimes tells that some A.nsp has the same title id with B.nsz which is not the case. By using option -i to see the title ids of these files, they have different title ids. Is this abnormal or I misunderstood something ?

**Comment by deadair3210** [comment] 2019-11-10 15:56
If you are converting a nsp to nsz, wouldn't the titleid stay the same since it's still the same game

**Comment by nicoboss** [comment] 2019-11-10 17:41
> When doing the conversion from nsp to nsz, it sometimes tells that some A.nsp has the same title id with B.nsz which is not the case. By using option -i to see the title ids of these files, they have different title ids. Is this abnormal or I misunderstood something ?

Could you please give me two filenames + TitleIds + version wrongly considered as having the same TItleID as example so I can reproduce your issue. https://github.com/nicoboss/nsz/issues/20 still is in progress so some Enhanced File Existing Check related issues are expected. If you want to be sure things never break, I highly recommend using latest release instead of latest commit as I’m often directly working inside master.

> If you are converting a nsp to nsz, wouldn't the titleid stay the same since it's still the same game

Yes, it will stay the same but Enhanced File Existing Check only checks files that are in the destination file format so this shouldn't be an issue.

It's planed to disable Cnmt pharsing by default in the next few days but this issue should be fixed anyways because enabeling it will still be an option.

**Comment by a5723797** [comment] 2019-11-11 01:31
I will later provide more info and try to reproduce it when this happens again.

**Comment by a5723797** [comment] 2019-11-11 13:31
Please see if this helps. If this is not appropriate, please let me know, will remove it.

D:\Games\nsz-2.0>py nsz.py -l 22 -C "..\\NS\\Dragon's Dogma Dark Arisen [010032C00AC58000][SwitchBounty].nsp"
                        ,;:;;,
                       ;;;;;
               .=',    ;:;;:,
              /_', "=. ';:;:;
              @=:__,  \,;:;:'
                _(\.=  ;:;;'
               `"_(  _/="`
                `"'
Atelier Ryza Ever Darkness & the Secret Hideout [0100D1900EC80000][v0][SwitchBounty].nsz with the same title ID  but a different filename already exists in the output directory.
If you want to continue with Dragon's Dogma Dark Arisen [010032C00AC58000][SwitchBounty].nsz keeping booth files use the -w parameterx!
fin

D:\Games\nsz-2.0>py nsz.py -i "..\\NS\\Dragon's Dogma Dark Arisen [010032C00AC58000][SwitchBounty].nsp"
                        ,;:;;,
                       ;;;;;
               .=',    ;:;;:,
              /_', "=. ';:;:;
              @=:__,  \,;:;:'
                _(\.=  ;:;;'
               `"_(  _/="`
                `"'

PFS0

magic = b'PFS0'
fsType = None
cryptoType = Crypto.NONE
size = 12950734067
offset = 0 - (0)

        ****************************************************************


        Files:

        File Path: b13374f5fb8d816b32e917cfcee656e2.cnmt.xml
        File Size: 1433

        ****************************************************************


        NCA Archive

        File Path: 5184273582071542f2fc23cbd21bee8d.nca
        File Size: 12950372352
        magic = b'NCA3'
        titleId = 010032C00AC58000
        rightsId = b'00000000000000000000000000000000'
        isGameCard = 0x0
        contentType = Content.PROGRAM
        cryptoType = Crypto.NONE
        Size: 12950372352
        crypto master key: 0
        crypto master key2: 0
        key Index: 0
        key Block: b'00000000000000000000000000000000'
        key Block: b'00000000000000000000000000000000'
        key Block: b'e636ea0fe4a01d8a27dcbcc6f33dc4cb'
        key Block: b'00000000000000000000000000000000'
        build Id: DEB6B520BB1E0352EAAE90AAC407FE0800000000000000000000000000000000

        ****************************************************************


        NCA Archive

        File Path: db7c0450e23c76d71ed318630397f59a.nca
        File Size: 155136
        magic = b'NCA3'
        titleId = 010032C00AC58000
        rightsId = b'00000000000000000000000000000000'
        isGameCard = 0x0
        contentType = Content.CONTROL
        cryptoType = Crypto.NONE
        Size: 155136
        crypto master key: 0
        crypto master key2: 0
        key Index: 0
        key Block: b'00000000000000000000000000000000'
        key Block: b'00000000000000000000000000000000'
        key Block: b'122cbbcb6120893c8119a7648c82604a'
        key Block: b'00000000000000000000000000000000'

        ****************************************************************


        NCA Archive

        File Path: 1d134f6d8478e0381db3995c42bde307.nca
        File Size: 201216
        magic = b'NCA3'
        titleId = 010032C00AC58000
        rightsId = b'00000000000000000000000000000000'
        isGameCard = 0x0
        contentType = Content.MANUAL
        cryptoType = Crypto.NONE
        Size: 201216
        crypto master key: 0
        crypto master key2: 0
        key Index: 0
        key Block: b'00000000000000000000000000000000'
        key Block: b'00000000000000000000000000000000'
        key Block: b'0acd4909696296e287d6f04a1f204b77'
        key Block: b'00000000000000000000000000000000'

        ****************************************************************


        NCA Archive

        File Path: b13374f5fb8d816b32e917cfcee656e2.cnmt.nca
        File Size: 3584
        magic = b'NCA3'
        titleId = 010032C00AC58000
        rightsId = b'00000000000000000000000000000000'
        isGameCard = 0x0
        contentType = Content.META
        cryptoType = Crypto.NONE
        Size: 3584
        crypto master key: 0
        crypto master key2: 0
        key Index: 0
        key Block: b'00000000000000000000000000000000'
        key Block: b'00000000000000000000000000000000'
        key Block: b'9b46ecef515f12f1636f76abf9e77458'
        key Block: b'00000000000000000000000000000000'

        ****************************************************************

fin

D:\Games\nsz-2.0>py nsz.py -i "..\\NS\\Atelier Ryza Ever Darkness & the Secret Hideout [0100D1900EC80000][v0][SwitchBounty].nsz"
                        ,;:;;,
                       ;;;;;
               .=',    ;:;;:,
              /_', "=. ';:;:;
              @=:__,  \,;:;:'
                _(\.=  ;:;;'
               `"_(  _/="`
                `"'

PFS0

magic = b'PFS0'
fsType = None
cryptoType = Crypto.NONE
size = 2205830500
offset = 0 - (0)

        ****************************************************************


        Files:

        File Path: 0100d1900ec800000000000000000008.cert
        File Size: 1792

        ****************************************************************


        Ticket

        File Path: 0100d1900ec800000000000000000008.tik
        File Size: 704
        signatureType = TicketSignature.RSA_2048_SHA256
        keyType = 0
        masterKeyRev = 8
        ticketId = 0000000000000000
        deviceId = 0000000000000000
        rightsId = 0100D1900EC800000000000000000008
        accountId = 00000000
        titleId = 0100D1900EC80000
        titleKey = 5350B88CE1CD74F8802F21349B050AA7
        titleKeyDec = b'8b9cdc609bfa50932252b7c0ed98bc10'

        ****************************************************************

        File Path: 3afd8917f3ddf09bdce7e201fd7a3d2d.ncz
        File Size: 2205362596

        ****************************************************************


        NCA Archive

        File Path: 0080c0f34c41460cb23844bbc47a275e.nca
        File Size: 140800
        magic = b'NCA3'
        titleId = 0100D1900EC80000
        rightsId = b'00000000000000000000000000000000'
        isGameCard = 0x0
        contentType = Content.MANUAL
        cryptoType = Crypto.NONE
        Size: 140800
        crypto master key: 2
        crypto master key2: 8
        key Index: 0
        key Block: b'00000000000000000000000000000000'
        key Block: b'00000000000000000000000000000000'
        key Block: b'a0dd673d27ec4831a6f4aad32964efef'
        key Block: b'00000000000000000000000000000000'

        ****************************************************************


        NCA Archive

        File Path: 81c8ee7648822abca766a3641e4f107d.cnmt.nca
        File Size: 3584
        magic = b'NCA3'
        titleId = 0100D1900EC80000
        rightsId = b'00000000000000000000000000000000'
        isGameCard = 0x0
        contentType = Content.META
        cryptoType = Crypto.NONE
        Size: 3584
        crypto master key: 2
        crypto master key2: 8
        key Index: 0
        key Block: b'00000000000000000000000000000000'
        key Block: b'00000000000000000000000000000000'
        key Block: b'86870e3887db4e7a340e67a9c4b515cf'
        key Block: b'00000000000000000000000000000000'

        ****************************************************************


        NCA Archive

        File Path: 7da6e5eeb620d1faccf76b409f5b7a9d.nca
        File Size: 288256
        magic = b'NCA3'
        titleId = 0100D1900EC80000
        rightsId = b'00000000000000000000000000000000'
        isGameCard = 0x0
        contentType = Content.CONTROL
        cryptoType = Crypto.NONE
        Size: 288256
        crypto master key: 2
        crypto master key2: 8
        key Index: 0
        key Block: b'00000000000000000000000000000000'
        key Block: b'00000000000000000000000000000000'
        key Block: b'90724c7bf400262a5073f66747bb5d81'
        key Block: b'00000000000000000000000000000000'

        ****************************************************************

fin

**Comment by nicoboss** [comment] 2019-12-21 11:48
Could you please try on latest if this issue still occurs and post another log if it does? https://github.com/nicoboss/nsz/commit/dcdb62f108d0d6915a6e245cf74fc1e9fc1b3c7c and https://github.com/nicoboss/nsz/commit/0bf8ef24c01107ce6f4404d935e1f8d41eb50d5b potentially fixed this.

**Comment by nicoboss** [comment] 2019-12-24 01:34
I assume NSZ 3.0 fixes this. If not please provide further information and reopen this issue.

**Closed by nicoboss** 2019-12-24 01:34 UTC
