### ISSUE TITLE
GUI not optional on latest PIP release

### ISSUE THREAD

**Issue by eXhumer** [nicoboss/nsz#63] opened 2020-04-14 21:47 UTC
#58 suggests that the pip package is supposed to be CLI only with the GUI requiring `nszgui` package to be installed. But trying to install `nsz` from pip still attempts to install the GUI also.

**Comment by nicoboss** [comment] 2020-04-15 23:06
I'm aware of that latest pip release from 29 Dec 2019 doesn't contain PR #58 and any other changes made since then. There’s currently a huge issue caused by https://github.com/nicoboss/nsz/commit/5b3afac2efeb6221ffa8411a12165229c21b4589 and reported in #52 which makes current master absolutely unusable as it produces corrupted files on either compression or decompression. Reverting it also isn't really an option as it fixes compression/decompression on a huge amount of XCI games. In the current release this XCI files basically only contained uncompressed NCA files because of them being skipped due to a first section offset different from 0x4000. I really try to find time fixing that bug as soon as possible but finding time beside University is always quite hard. I hopefully will be able to look into it somewhere in the following weak but really can't promise. If you like you can also try fixing it by your own. As soon that's fixed there will be another release also resolving this issue.

**Comment by eXhumer** [comment] 2020-04-16 15:18
I will look into the issue you mentioned and see if I can fix it.

**Comment by eXhumer** [comment] 2020-04-16 17:31
UPDATE: I don't think there is any issue with the commit you mentioned. I compressed files just fine on the latest commit of the script and it compresses/decompresses/verifies 3 of the files mentioned that apparently doesn't work.

**Comment by eXhumer** [comment] 2020-04-16 17:37
Compression result of one of the mentioned files.
https://github.com/nicoboss/nsz/issues/52#issuecomment-614792151

**Comment by nicoboss** [comment] 2020-09-06 11:48
With the latest NSZ v4.0 release GUI is now optional. See https://pypi.org/project/nsz/4.0.0/
To install the CLI verion: `pip3 install --upgrade nsz`
To install the GUI verion: `pip3 install --upgrade nsz[gui]`
See https://github.com/nicoboss/nsz#installation for full NSZ v4.0 installation instruction

**Closed by nicoboss** 2020-09-06 11:48 UTC
Labels: deployment
