### ISSUE TITLE
Verifying files flagging up good files as corrupted

### ISSUE THREAD

**Issue by gut5** [nicoboss/nsz#22] opened 2019-10-28 10:30 UTC
Overzealous verify check may be flagging up normal NCA files, or it may just be that some files always show up as corrupted. Used the commit from about 2 days ago.

**Comment by nicoboss** [comment] 2019-10-28 12:36
Please poste an example of a good file flagged as corrupted so I can reproduce your issue. Verification checks sha256 hash of the reconstructed nca file with its filename. If the hash it doesn't match it's very likely something went wrong or the file was improperly modified.

**Comment by gut5** [comment] 2019-10-28 16:13
Annoyingly I don't have a good example on me right now (currently outside) but I did notice the issue happen on this file (Work x Work JPN, it's a scene release so I assume it's "good").

The output I get is 

`[VERIFY NSZ] hr-ahnra.nsz
911MB/s [00:17, 51.2MB/s/s]                                                     
[CORRUPTED]  1a8e83c1267620de353fa01a638246cd.ncz
[CORRUPTED]  be631eaefe16b016c1ba03874db04913.nca
[CORRUPTED]  e60fc40869455441bf880bf0dad603b5.nca
[EXISTS]     197d5eac29d3e9f2bdf637a7f876a7a3.cnmt.nca
[EXISTS]     197d5eac29d3e9f2bdf637a7f876a7a3.cnmt.xml
fin
`

**Comment by nicoboss** [comment] 2019-10-28 17:06
That game is like 5,478円 on the eshop which is more than 50$ so I won't buy it. You also mentioned other games having similar issues so just report another one once your home. I might start verifying some games I dumped in the past to see if I can recreate your issue in the meantime.

**Comment by gut5** [comment] 2019-10-28 18:19
Oh no, I didn't realize testing this would incur you costs, I would want to avoid that. Is there a way I can demonstrate this without costing you money?

**Comment by nicoboss** [comment] 2019-10-28 19:55
Usually I don't mind buying games for testing as they are often quite fun however I prefer European/American games especially if they are that expensive and a western version is already announced. In case of Work x Work its, western version named Heroland will be released at 5. Dez 2019.
I just tested a few hundred games and none of them were flagged as CORRUPTED so a bug seems unlikely. It seems like you using scene releases is the cause of the issue. They probably removed certificates what would cause the NCA hash check to fail as they were modified. That your game doesn't contain a Ticket further proofs my point. This also explain why uncompressed NCAs are also flagged as CORRUPTED which shouldn't even be possible as they are completely untouched by my tool. The game probably was already repacked by scene using standard crypto instead of titlekey crypto and so modifying data without modifying the filenames.
It would be interesting to know if they at least fixed the hashes inside Cnmt. If so, we could just use that ones instead of the filename. To test this, I modified NSZ to print the Cnmt data into the console.
Please get latest commit from the Cnmt_hash_test branch, put ONLY your as CORRUPTED flagged file into the same folder and execute “python .\nsz.py -C” without specifying any file to compress. Then just Post what you see in the console.

**Comment by Mat37** [comment] 2019-10-31 20:36
The same happens for me with Oninaki (TID 01001AF00CE54000) with level 22 solid compression and with the latest commit at time of writing this. I ran the command twice just to be sure and get the same error as above (with different NCA names ofc). I'm pretty sure the NSP is good since i installed it on my Switch and played without any problem.

**Comment by nicoboss** [comment] 2019-10-31 22:57
@Mat37 Please get latest commit from the Cnmt_hash_test branch, put ONLY your as CORRUPTED flagged file into the same folder and execute “python .\nsz.py -C” without specifying any file to compress. Then post what you see in the console. This will help a lot to figure out how to solve this issue. Read my last command if you are interested why this issue probably occurs.

**Comment by Mat37** [comment] 2019-11-02 09:29
I tried your command in the Cnmt_hash_test branch with only my NSP that is flagged as corrupted once compressed and got this log but i feel like i did something wrong.
[1.txt](https://github.com/nicoboss/nsz/files/3800315/1.txt)
So just in case i tried giving the NSP as argument and got this
[2.txt](https://github.com/nicoboss/nsz/files/3800316/2.txt)

**Comment by nicoboss** [comment] 2019-11-02 16:43
Thanks a lot for your console log. Seems as if scene releases hashed their modified files and patched the hashes inside Cnmt so the Nintendo Switch doesn't see them as corrupted. That's great news because it makes it possible to fix this issue by using the hashes from the Cnmt instead of the filename. I’ve never seen a scene release as I don’t pirate games so there really was no way for me to know that they don’t change the filename to the new hash after modifying their games.

**Closed** 2019-11-03 02:14 UTC
