### ISSUE TITLE
block compressing + verify will stuck at the verify 99% progress

### ISSUE THREAD

**Issue by skygunner** [nicoboss/nsz#39] opened 2019-12-15 15:56 UTC
Windows 10, 
tested build 
nsz_v2.1.1_win64_portable.zip
nsz_nuitka_ab76c8e_portable.zip

parameters:
block compressing, default size, level 18, -w -V --rm-source

solid compressing with level 22 seems does the same thing

Problem with files:
[01003BC0000A0800][v2031616].nsp
[0100152000022800][v589824].nsp

**Comment by nicoboss** [comment] 2019-12-15 16:11
Your issue is probably a duplicate of https://github.com/nicoboss/nsz/issues/25 which was already fixed last week. NSZ 3.0 will be release later today which will include the bugfix for Issue #25.

That this issue also occurs for solid compression is wired as the original issue only affected block compression. Further information is required. What game causes this problem when solid compressing it? Maybe try again to ensure it really occurred with solid compression.

**Comment by nicoboss** [comment] 2019-12-15 16:22
Interesting bug report of a similar issue occurred on GBATemp inside the "NSZ - Homebrew compatible NSP/XCI compressor/decompressor" thread from byanime which could potentially be related:
```
It seems when using solid compressing level 22, or when using block compressing 18 + verify + delete source, the programm will stuck at the 98% ~ 100% for minutes without going further. Eventually it will finish.

I tried
nsz_nuitka_ab76c8e_portable.zip

Windows 10
```
```
I used this for compressing all .nsp files in current folder and subfolders
forfiles /s /m *.nsp /c "cmd /c D:\nsz\nsz.exe -C --level 18 --block --threads 4 @path"

and used this for decompressing
forfiles /s /m *.nsz /c "cmd /c D:\nsz\nsz.exe -D --threads 4 @path"

Works very well.

However the verify part doesn't seem to work , stuck at 99% for ages
```

**Comment by nicoboss** [comment] 2019-12-15 16:37
My answer on GBATemp:
```
Your issue could be related to https://github.com/nicoboss/nsz/issues/39 which was fixed last week and it’s fix will be in the NSZ 3.0 which will be released later today.
Only strange that it eventually finishes for you while the on skygunner's seem to be stuck forever like in the last week fixed https://github.com/nicoboss/nsz/issues/25 but he also mentioned it occurring for solid compression which clearly contradicts Issue #25 so you probably describe the same issue but just were more patient then skygunner. Please provide as much information as you can like for which game this issue occurs. Because of https://github.com/nicoboss/nsz/issues/31 the process bar is currently bugged for solid multithreaded compression however this won't occur on block compression but still make sure it's not what causes you to think it's stack even though NSZ is working hard just without showing it on the process bar. Monitor disk and CPU activities using the preinstalled Windows Resource Monitor while it's stuck. It could be something disk caching related where Windows is caching everything in RAM and then is forced to write it on your slow HDD wile verifying. Please just try gathering as much information as possible and report back with everything you found out.
```

**Comment by skygunner** [comment] 2019-12-15 17:25
Problem with files, for example
[01003BC0000A0800][v2031616].nsp
[0100152000022800][v589824].nsp
Verify stuck at 100%, disk io is 0%, verify passed time and speed is pasued, not changing, progress is at 100%.  This happens at 
-C -B -l 18 -t 4 -V , with or without remove source

**Comment by nicoboss** [comment] 2019-12-15 17:38
The -B command line argument enables block compression. Is there any case where it happens without Block compression? As soon block compression is involved it's for sure a dublicate of https://github.com/nicoboss/nsz/issues/25.

**Comment by skygunner** [comment] 2019-12-15 17:48
The same files having block comperssing verify problem would usually have similar problem when doing solid high level compressing , for example
[01003BC0000A0800][v2031616].nsp
-C -l 22 -w -t 4 
When the compressing reached 99% progress, the progress will stall for 5 minutes or longer, the memory useage is about 4.9GB, cpu usage is average 25% on i7 4770.
The disk write speed reported is about 1.X MB/s for 98% of the time, the rest 2% would have a bust rate of around 80MB/s

Finally it would complete with output information:

2.72GB [05:53, 7.70MB/s]
compressed 76% 2717023744 -> 2079396467  - 345db18461c99ad96fe142982b1aff13.nca
[ADDING]     73c38f1fb87b914fd4f66c00c21e569d.nca 181760 bytes to NSP
[ADDING]     bd56b50fff57c080dd81755a01a0ed9d.nca 3365376 bytes to NSP
skipping delta fragment
skipping delta fragment
skipping delta fragment
skipping delta fragment
skipping delta fragment
skipping delta fragment
[ADDING]     576c542826ff46f61fcb7623294f1bbd.cnmt.nca 11264 bytes to NSP
[ADDING]     576c542826ff46f61fcb7623294f1bbd.cnmt.xml 3134 bytes to NSP
[ADDING]     f1da161dd1636f045cbb90d425777f70.nca 400896 bytes to NSP
Done!

I understand high level compressing would need huge memory. But it seems when the progress bar has reached 99%, only 1% or 10% work has been done. 
And the whole process for a file compressing with level 22 seems to take 10 minutes or more, is that normal?

**Comment by nicoboss** [comment] 2019-12-15 18:09
What you describe now with solid compression is exactly https://github.com/nicoboss/nsz/issues/31
The problem is the -t 4 you are using for solid compression.

Just use a single thread and you are fine. There is no easy way of fixing this issue as it's how zStandard handles multithreaded compression. However, keep in mind that this is only a visual bug and the whole compression process would take exactly the same amount of time even after fixing this. 

The performance gain of using multiple threads for solid compression is near zero anyways as unlike block compression there is very little to parallelize. I the future I will probably add task level parallelization to at least parallelize solid compression of multiple games. If you want faster compression speed use by using multithreading use block compression and if you care about compression speed decrees the compression level. See https://gist.github.com/nicoboss/62ae92c5dd0d44088323dc8b37859abf if you wonder how different compression levels impact the compression ratio for solid compression.

**Comment by skygunner** [comment] 2019-12-15 18:12
Cool, so for solid compressing, just use single thread. 
For block compressing, use multithread.

**Comment by nicoboss** [comment] 2019-12-15 20:45
Thanks for testing solid multithreaded compression speed. Didn't thought there's such a major performance difference. zStandards internal multithreaded compression mode is much better than I thought. In that case just use multithreaded solid compression and ignore the visual glitch. Scene is using solid compression with level 22 and 3 threads- now I know why.

**Comment by blawar** [comment] 2019-12-16 00:36
Using 4 cores to cut the compression time in half is not good.  You would have been better served to compress 4 files independently for a 4x speed up instead of 4 (assuming no bottlenecks in other subsystems).

**Closed** 2019-12-20 22:19 UTC
