### ISSUE TITLE
Memory issue when verifying/decompressing

### ISSUE THREAD

**Issue by Mat37** [nicoboss/nsz#21] opened 2019-10-26 19:13 UTC
When trying to decompress or verify big games (4GB+ i think) with these parameters : -C -w -V -l 22 -B
At some point i run out of RAM (i only have 8GB) and it just crashes.
Here's the log for a 6.6GB game
[1.txt](https://github.com/nicoboss/nsz/files/3775176/1.txt)
Here it crashed during verification but the same happens during decompression.

**Comment by nicoboss** [comment] 2019-10-26 19:54
In the logfile you are posting you are compressing and not decompressing which would make this issue a duplicate of #13

Can you confirm this also happens when decompressing or verifying? Anyways I now also lowered the buffer of NszDecompressor and BlockCompressor to highly reduce any memory impact such a memory leak would have.

Please get latest master and see the memory leak no longer fills your whole RAM there. It’s expected to leak at least 10 times less. More research what causes this leak in the first place will be done later.

**Comment by Mat37** [comment] 2019-10-27 09:09
In the log i posted the error happened during verificaton, the compression was already done since the ratio is there and the [VERIFY NSZ] step had already begun.
I just tried with the new master and the same happens during verification
[newlog.txt](https://github.com/nicoboss/nsz/files/3775658/newlog.txt)
I don't know why it says error during compression tho since all went fine during this step

**Comment by nicoboss** [comment] 2019-10-27 10:27
Thanks a lot for reporting this issue.  Your right I missed that it only occurs when block compression is used. When block compressing this game as NSZ and later verifying it really leaks over 11 GB RAM when verifying it's NSZ. No memory is leaked occurs during the block compression process. Everything went fine if solid compression is used. You are probably one of the first person ever testing block decompression so great you found that issue. I have 64 GB RAM inside my PC so I completely missed that. Memory leaks in python really suck - they are so hard to find. Especially if they are inside NUT, a library blawar wrote and I haven’t really much looked into it. Until this issue is fixed you can just use a large Page file or extract the NS, use IndependentNczDecompressor.py which shouldn’t leak and repack as NSP.

**Comment by Mat37** [comment] 2019-10-27 10:46
I use block compression because i plan on using nsz on Yuzu/Switch directly, and iirc solid compression won't be able to do that. I guess i'm going with a large pagefile since extracting, decompressing and repacking seems quite long and you can't really verify the NSZ right after compression i think.

**Comment by noko631405** [comment] 2019-10-27 18:00
Hello

**Closed** 2019-10-29 19:44 UTC
Labels: bug, good first issue, memory leak

**Comment by iexa** [comment] 2019-10-30 03:58
@Mat37: the way I see it nsz / nsp files _must be_ installed on the switch; they cannot be run using the file directly from an sd card or external storage. XCI files should be created with block compression (bs=2^19 - 2^22=0.5-4mb b.size imho)  if that's what you want to achieve.

**Comment by nicoboss** [comment] 2019-10-30 08:49
@iexa @Mat37 Technically booth NSZ and XCZ can be mounted and be played on and Emulators/Real hardware without installation. Block compressed NSZ files are quite confusing as people expect XCZ to be the mountable format. XCZ will use block compression by default while NSZ uses solid compression by default. I generally recommend using NSZ for solid and XCZ for block compression as otherwise there’s no way to know if a certain NSZ/XCZ can be mounted. I'm quite unhappy about that the same file extension sometimes having mounting support and sometimes doesn’t depending if block compression or solid compression was used. I even considering changing the file extension for block compressed files but that's also quite strange as NSZ/XCZ just means the container can contain compressed NCZ files so should I make them NCZB, NSZB, XCZB or what? Having different extensions for the same file format generally is kind of wired. Except mounting booth compression types have the same features and everything that supports solid compressed NCZ should also support block compressed NCZ (which currently isn't the case but will be in the future). The reason why this script currently doesn’t support XCZ is because XCI packing isn’t implemented yet. If you have any suggestion how to go forward with block compressed NCZ files just let me know.

**Comment by nicoboss** [comment] 2019-10-30 17:52
Recognizing if solid or block compression was used is extremely easy to program and already implemented. That's the reason why you don't have to specify it when decompressing. I definitely should improve the -i command to show such nsz/xcz exclusive information and all the information it would normally show for an uncompressed nca it just didn't had priority so far.
